### ISSUE TITLE
LFN panel says "Squiky Labs"

### ISSUE THREAD

**Issue by stepton-thudfoot** [squinkylabs/SquinkyVCV#67] opened 2019-04-19 19:51 UTC
It's surprisingly easy to miss.

**Comment by squinkylabs** [comment] 2019-04-20 18:52
I guess the problem is that it is so low that it gets obscured if the CPU meters are on? It is small, but not that small. Will consider moving everything up a few pixels - there's room.

**Comment by stepton-thudfoot** [comment] 2019-04-25 06:41
I'm not sure I was understood--there's a typo on the panel. It says "Squiky Labs" instead of "Squinky Labs".

**Comment by squinkylabs** [comment] 2019-04-25 14:54
Oh! So it does. Thanks for the persistence.

**Comment by squinkylabs** [comment] 2019-06-05 15:32
fixed in current release

**Closed by squinkylabs** 2019-06-05 15:32 UTC
Labels: bug
